name: getHackNews

on:
  # push:
  schedule:
    - cron: '0 */10 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run getHackNews'
        run: sh ./_topHackNews/runHackNews.sh